server:
  port: 0
spring:
  application:
    name: eureka
  cloud:
    config:
      profile: dev
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  renewalPercentThreshold: 0.85




#Monitoreo con Actuator-Prometheus y Grafana.
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true